USERPATH: "/Users/gian"
PROJECTPATH: "/Users/gian/ml-gle"
RAW_DATAPATH: "/Users/gian/ml-gle/data/melt/raw"
READY_DATAPATH: "/Users/gian/ml-gle/data/melt/ready"
SAVEPATH: "/Users/gian/ml-gle/save/melt"




